***********************************************************;
*  LESSON 1, PRACTICE 1                                   *;
*  a) In Enterprise Guide, use the Servers list to expand *;
*     Servers => Local => Libraries => PG2. Double-click  *;
*     NP_FINAL to open the table. The table includes one  *;
*     row per US national park. Note that the first row   *;
*     in the table is Cape Krusenstern National Monument. *;
*  b) Become familiar with the following columns in the   *;
*     NP_FINAL table:                                     *;
*     1) Region (Alaska, Intermountain, Midwest, National *;
*        Capital, Northeast, Pacific West and Southeast)  *;
*     2) Type (Monument, Park, Preserve, River, Seashore) *;
*     3) ParkName (full name of national park)            *;
*     4) DayVisits (number of daily visitors in 2017)     *;
*     5) Campers (number of campers in 2017)              *;
*     6) OtherLodging (number of people in other lodging, *;
*        including cabins and hotels, in 2017)            *;
*     7) Acres (total park size in acres)                 *;
*  c) Click the DATA step markers for debugging button    *;
*     to enable debugging in the program. Click on the    *;
*     Debugger icon next to the DATA statement. The DATA  *;
*     Step Debugger window will open.                     *;
*  d) How many variables are in the PDV? What are the     *;
*     initial values?                                     *;
*  e) Click the Step execution to next line button to     *;
*     execute the highlighted SET statement.              *;
*     Recall the first row of the NP_FINAL table is Cape  *;
*     Krusenstern National Monument. Why was the first    *;
*     row not read into the PDV in the first iteration    *;
*     of the DATA step?                                   *;
*  f) Click the Step execution to next line button to     *;
*     step through the remaining statements in the DATA   *;
*     step. Which statements are executable?              *;
*     Which statements are compile-time only?             *;
*  g) Exit the debugger and run the program to view the   *;
*     output table.                                       *;
***********************************************************;

data np_parks;
	set pg2.np_final;
	where Type="PARK";
	Type=propcase(Type);
	AvgMonthlyVisitors=sum(DayVisits,Campers,OtherLodging)/12;
	format AvgMonthlyVisitors Acres comma10.;
	keep Region ParkName AvgMonthlyVisitors Acres;
run;
