***********************************************************;
*  Controlling Column Output                              *;
***********************************************************;
*  Syntax                                                 *;
*                                                         *;
*    table(DROP=col1 col2...)                             *;
*    table(KEEP=col1 col2...)                             *;
***********************************************************;

***********************************************************;
*  Demo                                                   *;
*  1) Use the DROP= data set option to drop MaxWindMPH    *;
*     from the INDIAN table and MaxWindKM from the        *;
*     ATLANTIC table. Do not drop any columns from the    *;
*     PACIFIC table.                                      *;
*  2) Start the DATA step debugger. Note that MaxWindMPH  *;
*     and MaxWindKM are included in the PDV.              *;
*  3) Close the debugger, run the program, and examine    *;
*     the three output tables. MaxWindMPH has been        *;
*     dropped from the INDIAN table, MaxWindKM has been   *;
*     dropped from the ATLANTIC table, and the PACIFIC    *;
*     table has all columns.                              *;
*  4) Add a DROP= data set option in the SET statement to *;
*     drop MinPressure. Start the debugger. Notice that   *;
*     MinPressure is not included in the PDV.             *;
*  5) Close the debugger, run the program, and examine    *;
*     the three output tables. Confirm that MinPressure   *;
*     has been dropped from each table.                   *;
***********************************************************;

data indian atlantic pacific;
	set pg2.storm_summary; 
	length Ocean $ 8;
	Basin=upcase(Basin);
	StormLength=EndDate-StartDate;
	MaxWindKM=MaxWindMPH*1.60934;
	if substr(Basin,2,1)="I" then do;
		Ocean="Indian";
		output indian;
	end;
	else if substr(Basin,2,1)="A" then do;
		Ocean="Atlantic";
		output atlantic;
	end;
	else do;
		Ocean="Pacific";
		output pacific;
	end;
run;
